/** CSS custom properties set on :root in AppShell — use in sx/styles. */
export const themeVars = {
  textPrimary: 'var(--app-text-primary)',
  textSecondary: 'var(--app-text-secondary)',
  primary: 'var(--app-primary)',
  primaryLight: 'var(--app-primary-light)',
  onPrimary: 'var(--app-on-primary)',
  bg: 'var(--app-bg)',
  bgPaper: 'var(--app-bg-paper)',
  headerBg: 'var(--app-header-bg)',
  headerBgScrolled: 'var(--app-header-bg-scrolled)',
  headerBorder: 'var(--app-header-border)',
  border: 'var(--app-border)',
  borderSubtle: 'var(--app-border-subtle)',
  surface: 'var(--app-surface)',
  surfaceElevated: 'var(--app-surface-elevated)',
  hover: 'var(--app-hover)',
  accentBg: 'var(--app-accent-bg)',
  accentBorder: 'var(--app-accent-border)',
  shadow: 'var(--app-shadow)',
  inputBg: 'var(--app-input-bg)',
  inputText: 'var(--app-input-text)',
  overlay: 'var(--app-overlay)',
};
