import { colors, themeVars } from '../../constants/styles';

export const SignInStyles = {
  root: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    width: '100%',
    minHeight: { xs: 'auto', md: 520 },
  },
  hero: {
    flex: { md: '0 0 42%' },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    p: { xs: 3, md: 4 },
    background: `linear-gradient(145deg, ${themeVars.accentBg} 0%, ${themeVars.surface} 40%, transparent 100%)`,
    borderBottom: { xs: `1px solid ${themeVars.borderSubtle}`, md: 'none' },
    borderRight: { md: `1px solid ${themeVars.borderSubtle}` },
  },
  logo: {
    width: 56,
    height: 56,
    mb: 2,
  },
  heroTitle: {
    fontSize: { xs: 22, md: 26 },
    fontWeight: 800,
    color: colors.TEXT_WHITE,
    lineHeight: 1.2,
    mb: 1,
  },
  heroSubtitle: {
    fontSize: { xs: 14, md: 15 },
    color: colors.TEXT_GRAY,
    lineHeight: 1.55,
    maxWidth: 280,
  },
  formSide: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    py: { xs: 2.5, md: 4 },
    px: { xs: 2, md: 4 },
  },
  tabs: {
    display: 'inline-flex',
    p: 0.5,
    mb: 2.5,
    borderRadius: '12px',
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.border}`,
    gap: 0.5,
  },
  tab: (active: boolean) => ({
    cursor: 'pointer',
    px: 2.5,
    py: 0.9,
    borderRadius: '10px',
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: active ? colors.ON_PRIMARY : colors.TEXT_GRAY,
    bgcolor: active ? colors.ORANGE_ACTIVE : 'transparent',
    transition: 'all 0.2s',
    userSelect: 'none',
    '&:hover': {
      color: active ? colors.ON_PRIMARY : colors.ORANGE_LIGHT,
    },
  }),
  form: (isActive: boolean) => ({
    display: isActive ? 'block' : 'none',
    width: '100%',
    maxWidth: 380,
  }),
};
