import { colors } from "../../constants/styles";

export const SignInStyles = {
  root: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'stretch', md: 'space-between' },
    justifyContent: { xs: 'flex-start', md: 'space-between' },
    width: '100%',
    height: '100%',
    overflow: 'auto',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    transition: '.5s',
    paddingTop: { xs: '56px', md: '100px' },
    paddingBottom: { xs: '24px', md: 0 },
    paddingLeft: { xs: '16px', md: 0 },
    paddingRight: { xs: '16px', md: 0 },
    width: { xs: '100%', md: '30%' },
    minHeight: { xs: 'auto', md: '100%' },
  },
  background: {
    width: { xs: '100%', md: '70%' },
    minHeight: { xs: '180px', md: '100%' },
    flex: { xs: '0 0 auto', md: 1 },
    backgroundImage: `url(/landing/banner.png)`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
  },
  tabs: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: { xs: 4, md: 0 },
  },
  tab: (active: boolean) => ({
    cursor: 'pointer',
    color: active ? colors.ORANGE_ACTIVE : colors.TEXT_GRAY,
    borderBottom: active ? `2px solid ${colors.ORANGE_ACTIVE}` : '2px solid transparent',
    padding: { xs: '8px 12px', md: '2px 12px' },
    fontSize: { xs: '14px', md: '16px' },
    fontWeight: '500',
    transition: '.5s',
    '&:hover': {
      color: colors.ORANGE_LIGHT,
    },
  }),
  form: (isActive: boolean) => ({
    transform: isActive ? 'scale(1)' : 'scale(1)',
    display: isActive ? 'block' : 'none',
    overflow: 'hidden',
    transition: '.5s',
    width: '100%',
    maxWidth: '350px',
  }),
};