apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - service.yml
  - autoscaling.yml
  - deployment.yml


images:
- name: # TODO: add the image name 
  newTag: latest

