import { colors, themeVars } from '../../constants/styles';

export const PopUpStyles = {
  container: (isOpen: boolean) => ({
    position: 'fixed',
    inset: 0,
    backdropFilter: 'blur(8px)',
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    zIndex: 20,
    display: isOpen ? 'block' : 'none',
    opacity: isOpen ? 1 : 0,
    transition: 'opacity 0.25s',
  }),
  content: (isOpen: boolean) => ({
    position: 'fixed',
    inset: 0,
    zIndex: 21,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    p: { xs: 1.5, sm: 2, md: 3 },
    pointerEvents: isOpen ? 'auto' : 'none',
    opacity: isOpen ? 1 : 0,
    transition: 'opacity 0.25s',
  }),
  panel: {
    position: 'relative',
    width: '100%',
    maxWidth: 920,
    maxHeight: 'min(92vh, 640px)',
    overflow: 'auto',
    borderRadius: '24px',
    bgcolor: colors.BG_PAPER,
    color: colors.TEXT_WHITE,
    border: `1px solid ${themeVars.border}`,
    boxShadow: themeVars.shadow,
    WebkitOverflowScrolling: 'touch',
  },
  actions: {
    position: 'absolute',
    right: { xs: 10, md: 16 },
    top: { xs: 10, md: 16 },
    zIndex: 22,
  },
  cancelIcon: {
    cursor: 'pointer',
    color: colors.ORANGE_LIGHT,
    bgcolor: 'rgba(0,0,0,0.35)',
    borderRadius: '50%',
    p: 0.25,
    transition: 'color 0.2s, transform 0.2s',
    '&:hover': {
      color: colors.ORANGE_ACTIVE,
      transform: 'scale(1.05)',
    },
  },
};
