import axios from 'axios';
import { BACKEND_BASE_URL } from './constants';
import { IUser, IUserLogin, IUserRegistration } from '../types';
import { Dispatch } from 'redux';

export interface PaymentPopUpMeta {
  balance?: number;
  required?: number;
}

export const mainActionTypes = {
  SET_USER: 'SET_USER',
  SET_POP_UP_STATUS: 'SET_POP_UP_STATUS',
  SET_POP_UP_CONTENT: 'SET_POP_UP_CONTENT',
  SET_PAYMENT_POP_UP_OPEN: 'SET_PAYMENT_POP_UP_OPEN',
  SET_PAYMENT_POP_UP_META: 'SET_PAYMENT_POP_UP_META',
};

export const forceDownload = (url: string) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url, true);
  xhr.responseType = 'blob';
  xhr.onload = function () {
    const urlCreator = window.URL || window.webkitURL;
    const imageUrl = urlCreator.createObjectURL(this.response);
    const tag = document.createElement('a');
    tag.href = imageUrl;
    tag.download = 'Generated by VAi';
    document.body.appendChild(tag);
    tag.click();
    document.body.removeChild(tag);
    urlCreator.revokeObjectURL(imageUrl);
  };
  xhr.send();
};

export const signInUser = async (user: IUserLogin) => {
  try {
    const res = await axios.post(`${BACKEND_BASE_URL}/auth/login`, user);
    return res.data;
  } catch (e: any) {
    return e?.response?.data;
  }
};

export const registerUser = async (user: IUserRegistration) => {
  try {
    const res = await axios.post(`${BACKEND_BASE_URL}/auth/register`, user);
    return res.data;
  } catch (e: any) {
    return e?.response?.data;
  }
};

export const getUser = async (access_token: string) => {
  try {
    const res = await axios.post(`${BACKEND_BASE_URL}/auth/get-user`, { access_token });
    return res.data;
  } catch (e: any) {
    return e?.response?.data;
  }
};


export const setUser = (user: IUser | null) => async (dispatch: Dispatch) => {
  dispatch({
    type: mainActionTypes.SET_USER,
    data: user,
  });
}

export const setPopUpStatus = (status: boolean) => async (dispatch: Dispatch) => {
  dispatch({
    type: mainActionTypes.SET_POP_UP_STATUS,
    data: status,
  });
}

export const setPopUpContent = (content: React.ReactNode | null) => async (dispatch: Dispatch) => {
  dispatch({
    type: mainActionTypes.SET_POP_UP_CONTENT,
    data: content,
  });
};

export const openPaymentPopUp =
  (meta?: PaymentPopUpMeta) => async (dispatch: Dispatch) => {
    dispatch({
      type: mainActionTypes.SET_PAYMENT_POP_UP_META,
      data: meta || null,
    });
    dispatch({
      type: mainActionTypes.SET_PAYMENT_POP_UP_OPEN,
      data: true,
    });
  };

export const closePaymentPopUp = () => async (dispatch: Dispatch) => {
  dispatch({
    type: mainActionTypes.SET_PAYMENT_POP_UP_OPEN,
    data: false,
  });
  dispatch({
    type: mainActionTypes.SET_PAYMENT_POP_UP_META,
    data: null,
  });
};