import { colors, themeVars } from '../../constants/styles';

export const ToolPageStyles = {
  page: {
    maxWidth: 1200,
    mx: 'auto',
    px: { xs: 2, sm: 3, md: 4 },
    pb: { xs: 5, md: 8 },
    pt: { xs: 1, md: 2 },
  },
  header: {
    textAlign: 'center',
    mb: { xs: 3, md: 4 },
  },
  eyebrow: {
    display: 'inline-block',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: colors.ORANGE_ACTIVE,
    mb: 1,
  },
  title: {
    color: colors.TEXT_WHITE,
    fontSize: { xs: 28, sm: 34, md: 40 },
    fontWeight: 800,
    lineHeight: 1.12,
  },
  titleAccent: {
    color: colors.ORANGE_LIGHT,
    fontSize: { xs: 28, sm: 34, md: 40 },
    fontWeight: 800,
    lineHeight: 1.12,
  },
  description: {
    color: colors.TEXT_GRAY,
    fontSize: { xs: 15, md: 17 },
    lineHeight: 1.6,
    maxWidth: 640,
    mx: 'auto',
    mt: 1.5,
  },
  creditsBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    px: 1.5,
    py: 0.75,
    borderRadius: '999px',
    fontSize: 13,
    fontWeight: 600,
    color: colors.TEXT_GRAY,
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.border}`,
  },
  creditsIcon: {
    fontSize: 16,
    color: colors.ORANGE_LIGHT,
  },
  panel: {
    p: { xs: 2, md: 2.5 },
    borderRadius: '20px',
    bgcolor: themeVars.surfaceElevated,
    border: `1px solid ${themeVars.border}`,
    boxShadow: themeVars.shadow,
  },
  panelSection: {
    mt: { xs: 2.5, md: 3 },
  },
  inputRow: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    gap: 1.5,
    alignItems: { md: 'stretch' },
  },
  inputGrow: {
    flex: 1,
    minWidth: 0,
  },
  centeredContent: {
    width: '100%',
    maxWidth: 840,
    mx: 'auto',
  },
  stylesSection: {
    mt: { xs: 3, md: 4 },
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  stylesSectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: colors.TEXT_GRAY,
    mb: 1.5,
    textAlign: 'center',
    width: '100%',
  },
  artStylesGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: { xs: 1.25, md: 1.75 },
    width: '100%',
    maxWidth: 840,
  },
  artStyleItem: {
    width: { xs: 88, sm: 96 },
    flexShrink: 0,
  },
  stylesGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: { xs: 1, md: 1.5 },
    maxWidth: 900,
    mx: 'auto',
  },
  resultsPage: {
    maxWidth: 1200,
    mx: 'auto',
    px: { xs: 2, sm: 3, md: 4 },
    pb: { xs: 5, md: 8 },
    pt: { xs: 1, md: 2 },
  },
  resultsPageHeader: {
    textAlign: 'center',
    mb: { xs: 2, md: 3 },
  },
  resultsPageTitle: {
    color: colors.TEXT_WHITE,
    fontSize: { xs: 26, sm: 32, md: 36 },
    fontWeight: 800,
    lineHeight: 1.12,
  },
  resultsPageTitleAccent: {
    color: colors.ORANGE_LIGHT,
    fontSize: { xs: 26, sm: 32, md: 36 },
    fontWeight: 800,
    lineHeight: 1.12,
  },
  alertWrap: {
    width: '100%',
    mb: { xs: 2, md: 2.5 },
  },
  resultsWorkspace: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: { xs: 2.5, md: 3 },
  },
  resultsLayout: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'minmax(0, 400px) minmax(0, 1fr)' },
    gap: { xs: 2.5, md: 3 },
    alignItems: 'stretch',
  },
  controlsCard: {
    p: { xs: 2, md: 2.5 },
    borderRadius: '20px',
    bgcolor: themeVars.surfaceElevated,
    border: `1px solid ${themeVars.border}`,
    boxShadow: themeVars.shadow,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    height: { md: '100%' },
  },
  controlsCardBadge: {
    display: 'flex',
    justifyContent: 'center',
  },
  resultsStylesBand: {
    width: '100%',
    p: { xs: 2, md: 2.5 },
    borderRadius: '20px',
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.borderSubtle}`,
  },
  sidebarCard: {
    p: { xs: 2, md: 2.5 },
    borderRadius: '20px',
    bgcolor: themeVars.surfaceElevated,
    border: `1px solid ${themeVars.border}`,
    position: { lg: 'sticky' },
    top: { lg: 100 },
  },
  sidebarTitle: {
    color: colors.ORANGE_LIGHT,
    fontSize: { xs: 22, md: 26 },
    fontWeight: 800,
    lineHeight: 1.15,
    mb: 0.5,
    display: { xs: 'none', lg: 'block' },
  },
  sidebarTitleAccent: {
    color: colors.TEXT_WHITE,
    fontSize: { xs: 22, md: 26 },
    fontWeight: 800,
  },
  mobileTitle: {
    display: { lg: 'none' },
    textAlign: 'center',
    mb: 2,
  },
  resultsArea: {
    p: { xs: 2, md: 2.5 },
    borderRadius: '20px',
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.borderSubtle}`,
    minHeight: { xs: 280, md: 420 },
    height: { md: '100%' },
    display: 'flex',
    flexDirection: 'column',
  },
  resultsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, 1fr)',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(2, 1fr)',
    },
    gap: { xs: 1.5, md: 2 },
  },
  resultsGridWide: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, 1fr)',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(3, 1fr)',
    },
    gap: { xs: 1.5, md: 2 },
    maxWidth: 900,
    mx: 'auto',
  },
  resultsGridLogo: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, 1fr)',
      sm: 'repeat(3, 1fr)',
    },
    gap: { xs: 1.5, md: 2 },
    width: '100%',
    maxWidth: 960,
    mx: 'auto',
  },
  imageCard: {
    position: 'relative',
    aspectRatio: '1',
    borderRadius: '16px',
    overflow: 'hidden',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    border: `1px solid ${themeVars.accentBorder}`,
    cursor: 'pointer',
    transition: 'transform 0.25s, box-shadow 0.25s',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 12px 32px rgba(0,0,0,0.35)',
      '& .tool-result-actions': {
        opacity: 1,
        transform: 'translateY(0)',
      },
    },
  },
  imageActions: {
    position: 'absolute',
    top: 8,
    right: 8,
    display: 'flex',
    gap: 0.5,
    opacity: 0,
    transform: 'translateY(-4px)',
    transition: 'opacity 0.2s, transform 0.2s',
  },
  imageActionsVisible: {
    opacity: 1,
    transform: 'translateY(0)',
  },
  actionIconBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: '10px',
    bgcolor: 'rgba(0,0,0,0.55)',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(255,255,255,0.15)',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    '&:hover': {
      bgcolor: colors.ORANGE_ACTIVE,
    },
  },
  emptyResults: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 280,
    color: colors.TEXT_GRAY,
    fontSize: 15,
    textAlign: 'center',
    p: 3,
  },
  uploadZone: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: 560,
    mx: 'auto',
    p: { xs: 4, md: 6 },
    borderRadius: '20px',
    border: `2px dashed ${themeVars.accentBorder}`,
    bgcolor: themeVars.accentBg,
    cursor: 'pointer',
    transition: 'all 0.25s',
    '&:hover': {
      borderColor: colors.ORANGE_LIGHT,
      bgcolor: themeVars.hover,
    },
  },
  uploadText: {
    color: colors.TEXT_GRAY,
    fontSize: 15,
    mt: 1.5,
    fontWeight: 500,
  },
  actionsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1.5,
    justifyContent: 'center',
    mt: 3,
  },
  sliderWrap: {
    maxWidth: 640,
    mx: 'auto',
    borderRadius: '18px',
    overflow: 'hidden',
    border: `1px solid ${themeVars.border}`,
    boxShadow: themeVars.shadow,
  },
};
