import { colors } from '../../constants/styles';

export const ZoomImageStyles = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 40,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(14px)',
    backgroundColor: 'rgba(0, 0, 0, 0.82)',
    p: { xs: 1.5, md: 2 },
  },
  toolbar: {
    position: 'absolute',
    top: { xs: 12, md: 20 },
    left: { xs: 12, md: 20 },
    right: { xs: 12, md: 20 },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    zIndex: 2,
  },
  toolbarGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 1,
    py: 0.5,
    borderRadius: '14px',
    bgcolor: 'rgba(20, 20, 28, 0.75)',
    border: '1px solid rgba(255,255,255,0.1)',
    backdropFilter: 'blur(12px)',
  },
  counter: {
    px: 1.5,
    py: 0.75,
    borderRadius: '10px',
    fontSize: 13,
    fontWeight: 700,
    color: colors.ORANGE_LIGHT,
    bgcolor: 'rgba(255, 140, 80, 0.15)',
    border: '1px solid rgba(255, 140, 80, 0.3)',
    letterSpacing: '0.04em',
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: '12px',
    color: colors.TEXT_WHITE,
    bgcolor: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.1)',
    transition: 'background-color 0.2s, transform 0.2s, border-color 0.2s',
    '&:hover': {
      bgcolor: 'rgba(255, 140, 80, 0.2)',
      borderColor: 'rgba(255, 140, 80, 0.45)',
      transform: 'scale(1.04)',
    },
  },
  iconBtnPrimary: {
    width: 44,
    height: 44,
    borderRadius: '12px',
    color: colors.TEXT_DARK,
    bgcolor: colors.ORANGE_ACTIVE,
    transition: 'background-color 0.2s, transform 0.2s',
    '&:hover': {
      bgcolor: colors.ORANGE_LIGHT,
      transform: 'scale(1.04)',
    },
  },
  stage: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    flex: 1,
    minHeight: 0,
    maxHeight: { xs: 'calc(100vh - 160px)', md: 'calc(100vh - 200px)' },
    px: { xs: 0, md: 6 },
  },
  navBtn: {
    flexShrink: 0,
    width: { xs: 44, md: 52 },
    height: { xs: 44, md: 52 },
    color: colors.TEXT_WHITE,
    bgcolor: 'rgba(20, 20, 28, 0.8)',
    border: '1px solid rgba(255,255,255,0.12)',
    backdropFilter: 'blur(8px)',
    transition: 'background-color 0.2s, transform 0.2s',
    '&:hover': {
      bgcolor: 'rgba(255, 140, 80, 0.25)',
      borderColor: 'rgba(255, 140, 80, 0.5)',
      transform: 'scale(1.05)',
    },
  },
  frame: {
    position: 'relative',
    maxWidth: { xs: '100%', md: 'min(900px, 78vw)' },
    maxHeight: '100%',
    width: '100%',
    borderRadius: { xs: '16px', md: '20px' },
    overflow: 'hidden',
    bgcolor: colors.TEXT_DARK,
    border: '1px solid rgba(255,255,255,0.12)',
    boxShadow: '0 32px 80px rgba(0,0,0,0.55)',
  },
  image: {
    display: 'block',
    width: '100%',
    maxHeight: { xs: 'calc(100vh - 200px)', md: 'calc(100vh - 240px)' },
    objectFit: 'contain',
  },
  thumbStrip: {
    position: 'absolute',
    bottom: { xs: 12, md: 20 },
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: 1,
    p: 1,
    borderRadius: '16px',
    bgcolor: 'rgba(20, 20, 28, 0.85)',
    border: '1px solid rgba(255,255,255,0.1)',
    backdropFilter: 'blur(12px)',
    maxWidth: 'calc(100vw - 32px)',
    overflowX: 'auto',
    zIndex: 2,
  },
  thumb: (active: boolean) => ({
    width: 56,
    height: 56,
    flexShrink: 0,
    borderRadius: '10px',
    overflow: 'hidden',
    cursor: 'pointer',
    border: active
      ? `2px solid ${colors.ORANGE_ACTIVE}`
      : '2px solid transparent',
    opacity: active ? 1 : 0.55,
    transition: 'opacity 0.2s, border-color 0.2s, transform 0.2s',
    '&:hover': {
      opacity: 1,
      transform: 'scale(1.05)',
    },
  }),
  thumbImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
};
