import { colors } from '../../constants/styles';

export const TransactionsPopUpStyles = {
  backdrop: (isOpen: boolean) => ({
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backdropFilter: 'blur(10px)',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    zIndex: 31,
    display: isOpen ? 'flex' : 'none',
    alignItems: 'center',
    justifyContent: 'center',
    p: 2,
  }),
  panel: {
    position: 'relative',
    width: '100%',
    maxWidth: 560,
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column',
    bgcolor: colors.BG_PAPER,
    color: colors.TEXT_WHITE,
    borderRadius: '20px',
    border: '1px solid rgba(255,255,255,0.12)',
    boxShadow: '0 32px 64px rgba(0,0,0,0.45)',
    overflow: 'hidden',
  },
  header: {
    px: { xs: 2, md: 3 },
    pt: { xs: 2.5, md: 3 },
    pb: 2,
    borderBottom: '1px solid rgba(255,255,255,0.08)',
    flexShrink: 0,
  },
  closeBtn: {
    position: 'absolute',
    right: { xs: 10, md: 14 },
    top: { xs: 10, md: 14 },
    color: colors.ORANGE_ACTIVE,
    cursor: 'pointer',
  },
  title: {
    fontSize: { xs: 22, md: 28 },
    fontWeight: 800,
    color: colors.ORANGE_LIGHT,
    pr: 4,
  },
  subtitle: {
    color: colors.TEXT_GRAY,
    fontSize: 14,
    mt: 0.5,
  },
  list: {
    flex: 1,
    overflow: 'auto',
    px: { xs: 1.5, md: 2 },
    py: 1.5,
    WebkitOverflowScrolling: 'touch',
  },
  empty: {
    py: 6,
    px: 2,
    textAlign: 'center',
    color: colors.TEXT_GRAY,
  },
};
