import { colors, themeVars } from '../../constants/styles';

export const HomeStyles = {
  page: {
    overflow: 'hidden',
  },
  section: {
    maxWidth: 1200,
    mx: 'auto',
    px: { xs: 2, sm: 3, md: 4 },
    py: { xs: 4, md: 6 },
  },
  hero: {
    position: 'relative',
    maxWidth: 1200,
    mx: 'auto',
    px: { xs: 2, sm: 3, md: 4 },
    pt: { xs: 3, md: 5 },
    pb: { xs: 4, md: 6 },
    textAlign: 'center',
  },
  heroGlow: {
    position: 'absolute',
    top: -40,
    left: '50%',
    transform: 'translateX(-50%)',
    width: { xs: 280, md: 520 },
    height: { xs: 280, md: 420 },
    borderRadius: '50%',
    background:
      'radial-gradient(circle, rgba(255,140,80,0.22) 0%, transparent 70%)',
    pointerEvents: 'none',
    zIndex: 0,
  },
  heroInner: {
    position: 'relative',
    zIndex: 1,
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    px: 1.5,
    py: 0.75,
    mb: 2.5,
    borderRadius: '999px',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: colors.ORANGE_LIGHT,
    bgcolor: 'rgba(255, 140, 80, 0.12)',
    border: '1px solid rgba(255, 140, 80, 0.35)',
  },
  heroTitle: {
    color: colors.TEXT_WHITE,
    fontSize: { xs: 34, sm: 44, md: 56 },
    fontWeight: 800,
    lineHeight: 1.08,
    mb: 2,
  },
  heroTitleAccent: {
    display: 'block',
    background: `linear-gradient(90deg, ${colors.ORANGE_LIGHT}, ${colors.ORANGE_ACTIVE})`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  heroDescription: {
    color: colors.TEXT_GRAY,
    fontSize: { xs: 16, md: 18 },
    fontWeight: 400,
    lineHeight: 1.65,
    maxWidth: 640,
    mx: 'auto',
    mb: 3.5,
  },
  heroActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1.5,
    justifyContent: 'center',
  },
  heroSecondaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    px: 2.5,
    py: 1.25,
    borderRadius: '12px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    color: colors.TEXT_WHITE,
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.border}`,
    transition: 'all 0.2s',
    '&:hover': {
      bgcolor: 'rgba(255, 140, 80, 0.12)',
      borderColor: 'rgba(255, 140, 80, 0.4)',
      color: colors.ORANGE_LIGHT,
    },
  },
  showcase: {
    maxWidth: 1200,
    mx: 'auto',
    px: { xs: 2, sm: 3, md: 4 },
    pb: { xs: 3, md: 5 },
  },
  showcaseGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, 1fr)',
      md: 'repeat(4, 1fr)',
    },
    gap: { xs: 1.25, md: 2 },
  },
  showcaseCard: {
    p: { xs: 1.5, md: 2 },
    borderRadius: '16px',
    textAlign: 'center',
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.borderSubtle}`,
    transition: 'all 0.25s',
    '&:hover': {
      borderColor: 'rgba(255, 140, 80, 0.35)',
      transform: 'translateY(-2px)',
      boxShadow: '0 12px 32px rgba(0,0,0,0.2)',
    },
  },
  showcaseValue: {
    color: colors.ORANGE_LIGHT,
    fontSize: { xs: 22, md: 28 },
    fontWeight: 800,
    lineHeight: 1.1,
    mb: 0.5,
  },
  showcaseLabel: {
    color: colors.TEXT_GRAY,
    fontSize: { xs: 11, md: 13 },
    fontWeight: 600,
    lineHeight: 1.3,
  },
  sectionEyebrow: {
    display: 'inline-block',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: colors.ORANGE_ACTIVE,
    mb: 1,
  },
  sectionTitle: {
    color: colors.TEXT_WHITE,
    fontSize: { xs: 26, md: 36 },
    fontWeight: 800,
    lineHeight: 1.15,
    mb: 1.5,
  },
  sectionDescription: {
    color: colors.TEXT_GRAY,
    fontSize: { xs: 15, md: 17 },
    lineHeight: 1.65,
    maxWidth: 720,
    mb: { xs: 3, md: 4 },
  },
  plusGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, 1fr)',
      lg: 'repeat(3, 1fr)',
    },
    gap: { xs: 1.5, md: 2 },
  },
  plusCard: {
    height: '100%',
    p: { xs: 2, md: 2.5 },
    borderRadius: '18px',
    bgcolor: 'rgba(255,255,255,0.03)',
    border: '1px solid rgba(255,255,255,0.08)',
    transition: 'all 0.25s',
    '&:hover': {
      borderColor: 'rgba(255, 140, 80, 0.35)',
      bgcolor: 'rgba(255, 140, 80, 0.06)',
      transform: 'translateY(-3px)',
      boxShadow: '0 16px 40px rgba(0,0,0,0.22)',
    },
  },
  plusIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 48,
    height: 48,
    borderRadius: '14px',
    mb: 1.5,
    bgcolor: 'rgba(255, 140, 80, 0.18)',
    border: '1px solid rgba(255, 140, 80, 0.35)',
    color: colors.ORANGE_LIGHT,
  },
  plusTitle: {
    color: colors.TEXT_WHITE,
    fontSize: { xs: 17, md: 19 },
    fontWeight: 700,
    mb: 0.75,
  },
  plusDescription: {
    color: colors.TEXT_GRAY,
    fontSize: { xs: 14, md: 15 },
    lineHeight: 1.55,
    fontWeight: 400,
  },
  productsGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: { xs: 2.5, md: 3.5 },
  },
  productCard: (active: boolean) => ({
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
    gap: { xs: 2, md: 3 },
    alignItems: 'center',
    p: { xs: 2, md: 3 },
    borderRadius: '24px',
    background: active
      ? 'linear-gradient(135deg, rgba(255,140,80,0.12) 0%, rgba(255,255,255,0.02) 50%)'
      : 'rgba(255,255,255,0.03)',
    border: active
      ? '1px solid rgba(255, 140, 80, 0.28)'
      : '1px solid rgba(255,255,255,0.08)',
    opacity: active ? 1 : 0.72,
    transition: 'all 0.25s',
    '&:hover': active
      ? {
          borderColor: 'rgba(255, 140, 80, 0.45)',
          boxShadow: '0 20px 48px rgba(0,0,0,0.25)',
        }
      : {},
  }),
  productVisual: {
    position: 'relative',
    aspectRatio: '4/3',
    borderRadius: '18px',
    overflow: 'hidden',
    bgcolor: 'rgba(0,0,0,0.25)',
    border: '1px solid rgba(255,255,255,0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productVisualImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  productVisualFallback: {
    fontSize: { xs: 64, md: 80 },
    color: 'rgba(255, 140, 80, 0.5)',
  },
  productTag: {
    display: 'inline-block',
    px: 1,
    py: 0.35,
    mb: 1,
    borderRadius: '8px',
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: colors.ORANGE_LIGHT,
    bgcolor: 'rgba(255, 140, 80, 0.14)',
    border: '1px solid rgba(255, 140, 80, 0.3)',
  },
  productTitle: {
    color: colors.ORANGE_LIGHT,
    fontSize: { xs: 24, md: 32 },
    fontWeight: 800,
    lineHeight: 1.15,
    mb: 1,
  },
  productDescription: {
    color: colors.TEXT_GRAY,
    fontSize: { xs: 14, md: 16 },
    lineHeight: 1.6,
    mb: 2,
  },
  footer: {
    mt: { xs: 4, md: 6 },
    pt: { xs: 3, md: 4 },
    pb: { xs: 3, md: 4 },
    borderTop: `1px solid ${themeVars.border}`,
    background:
      'linear-gradient(180deg, transparent 0%, rgba(255,140,80,0.04) 100%)',
  },
  footerInner: {
    maxWidth: 1200,
    mx: 'auto',
    px: { xs: 2, sm: 3, md: 4 },
  },
  footerTop: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'auto 1fr' },
    gap: { xs: 3, md: 4 },
    alignItems: { md: 'start' },
    mb: 3,
  },
  footerBrand: {
    maxWidth: 280,
  },
  footerLogo: {
    width: 52,
    cursor: 'pointer',
    mb: 1.5,
  },
  footerTagline: {
    color: colors.TEXT_GRAY,
    fontSize: 14,
    lineHeight: 1.55,
  },
  footerLinks: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr 1fr', sm: 'repeat(3, 1fr)' },
    gap: { xs: 2, md: 3 },
  },
  footerColTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: colors.TEXT_GRAY,
    mb: 1.25,
  },
  footerLink: {
    display: 'block',
    color: colors.TEXT_WHITE,
    fontSize: 14,
    fontWeight: 500,
    py: 0.5,
    cursor: 'pointer',
    transition: 'color 0.2s',
    '&:hover': { color: colors.ORANGE_LIGHT },
  },
  footerBottom: {
    display: 'flex',
    flexDirection: { xs: 'column', sm: 'row' },
    alignItems: { sm: 'center' },
    justifyContent: 'space-between',
    gap: 1,
    pt: 2.5,
    borderTop: `1px solid ${themeVars.borderSubtle}`,
  },
  footerCopyright: {
    color: colors.TEXT_GRAY,
    fontSize: 13,
  },
};
