apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vai-server-secret-global
  annotations:
    force-sync: "0"
  labels:
    app: vai-server-secret-global
    environment: production
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: vault-kv-prod
    kind: ClusterSecretStore
  target:
    name: vai-server-secret-global
  dataFrom:
    - extract:
        key: /VAI
