import { colors } from "../../constants/styles";

export const HeaderStyles = {
  container: (scrolling: boolean) => ({
    padding: { md: '22px 64px', xs: '8px 16px' },
    width: '100%',
    position: 'fixed',
    background: scrolling ? '#00000070' : 'transparent',
    backdropFilter: 'blur(10px)',
    transition: '.5s',
    zIndex: '19',
  }),
  logo: {
    width: { xs: '40px', md: '60px' },
    cursor: 'pointer',
  },
  menuItem: {
    cursor: 'pointer',
    color: colors.TEXT_GRAY,
    fontSize: { md: '16px', xs: '13px' },
    fontWeight: '500',
    transition: '.5s',
    '&:hover': {
      color: colors.ORANGE_LIGHT,
      transform: 'scale(1.05)',
    },
  },
  button: {
    padding: { md: '8px 32px', xs: '6px 16px' },
    fontSize: { xs: '13px', md: 'inherit' },
  },
  user: {
    fontSize: { md: '13px', xs: '12px' },
    fontWeight: '500',
    color: colors.ORANGE_ACTIVE,
    border: `1px solid ${colors.ORANGE_ACTIVE}`,
    padding: { md: '8px 14px', xs: '6px 8px' },
    borderRadius: '50px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: { md: '8px', xs: '4px' },
    maxWidth: { xs: '140px', sm: 'none' },
  },
  userName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: { xs: '72px', sm: 'none' },
  },
  logoutIcon: {
    cursor: 'pointer',
    currentColor: 'inherit',
    transition: '.5s',
    '&:hover': {
        transform: 'scale(.98)',
      },
  },
  mobileDrawer: {
    width: '82vw',
    maxWidth: '360px',
    backgroundColor: 'var(--app-bg-paper, #1f4058)',
    color: 'var(--app-text-primary, #fff)',
    borderLeft: '1px solid rgba(255,255,255,0.12)',
  },
  mobileDrawerInner: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1.25,
    padding: '20px 16px',
  },
  mobileDrawerTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '4px',
  },
  mobileDrawerItem: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    fontSize: '16px',
    fontWeight: 500,
    color: 'var(--app-text-primary, #fff)',
    padding: '8px 2px',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
  },
  mobileUserName: {
    fontSize: '14px',
    color: 'var(--app-text-secondary, #b7b7b7)',
    marginTop: '4px',
    marginBottom: '2px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};