import { colors, themeVars } from '../../constants/styles';

export const HeaderStyles = {
  shell: (scrolled: boolean) => ({
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 19,
    transition: 'background 0.3s, box-shadow 0.3s, border-color 0.3s',
    backdropFilter: scrolled ? 'blur(14px)' : 'blur(10px)',
    background: scrolled
      ? themeVars.headerBgScrolled
      : themeVars.headerBg,
    borderBottom: `1px solid ${themeVars.headerBorder}`,
    boxShadow: scrolled ? themeVars.shadow : 'none',
  }),
  inner: {
    maxWidth: 1280,
    mx: 'auto',
    px: { xs: 2, md: 3 },
    py: { xs: 1.25, md: 1.5 },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
  },
  left: {
    display: 'flex',
    alignItems: 'center',
    gap: { xs: 1, md: 3 },
    minWidth: 0,
  },
  logo: {
    width: { xs: 44, md: 56 },
    height: 'auto',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'transform 0.2s',
    '&:hover': { transform: 'scale(1.04)' },
  },
  nav: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    gap: 0.5,
  },
  navLink: (active: boolean) => ({
    cursor: 'pointer',
    px: 1.5,
    py: 0.75,
    borderRadius: '10px',
    fontSize: 14,
    fontWeight: 600,
    color: active ? colors.ON_PRIMARY : colors.TEXT_GRAY,
    bgcolor: active ? colors.ORANGE_ACTIVE : 'transparent',
    transition: 'color 0.2s, background-color 0.2s, transform 0.2s',
    whiteSpace: 'nowrap',
    '&:hover': {
      color: active ? colors.ON_PRIMARY : colors.TEXT_WHITE,
      bgcolor: active ? colors.ORANGE_LIGHT : themeVars.hover,
      transform: 'translateY(-1px)',
    },
  }),
  right: {
    display: 'flex',
    alignItems: 'center',
    gap: { xs: 0.5, md: 1 },
  },
  rightDesktop: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    gap: 1,
  },
  divider: {
    width: '1px',
    height: 28,
    bgcolor: themeVars.borderSubtle,
    mx: 0.5,
  },
  accountLink: (active: boolean) => ({
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 0.5,
    px: 1.25,
    py: 0.75,
    borderRadius: '10px',
    fontSize: 14,
    fontWeight: 600,
    color: active ? colors.ORANGE_LIGHT : colors.TEXT_GRAY,
    bgcolor: active ? themeVars.accentBg : 'transparent',
    transition: 'all 0.2s',
    '&:hover': {
      color: colors.ORANGE_LIGHT,
      bgcolor: themeVars.accentBg,
    },
  }),
  creditsPill: {
    display: { xs: 'none', md: 'inline-flex' },
    alignItems: 'center',
    gap: 0.5,
    px: 1.25,
    py: 0.6,
    borderRadius: '999px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 700,
    color: colors.ORANGE_LIGHT,
    bgcolor: themeVars.accentBg,
    border: `1px solid ${themeVars.accentBorder}`,
    transition: 'transform 0.2s, box-shadow 0.2s',
    '&:hover': {
      transform: 'scale(1.03)',
      boxShadow: themeVars.shadow,
    },
  },
  userChip: {
    display: { xs: 'none', md: 'inline-flex' },
    alignItems: 'center',
    gap: 1,
    pl: 0.5,
    pr: 0.75,
    py: 0.35,
    borderRadius: '999px',
    border: `1px solid ${themeVars.accentBorder}`,
    bgcolor: themeVars.accentBg,
  },
  userAvatar: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 800,
    color: colors.ON_PRIMARY,
    bgcolor: colors.ORANGE_ACTIVE,
    flexShrink: 0,
  },
  userName: {
    fontSize: 13,
    fontWeight: 600,
    color: colors.TEXT_WHITE,
    maxWidth: 120,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  logoutBtn: {
    color: colors.TEXT_GRAY,
    p: 0.5,
    '&:hover': { color: colors.ORANGE_LIGHT },
  },
  menuBtn: {
    display: { xs: 'flex', md: 'none' },
    color: colors.TEXT_WHITE,
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.border}`,
    borderRadius: '12px',
    '&:hover': {
      bgcolor: themeVars.accentBg,
      borderColor: themeVars.accentBorder,
    },
  },
  mobileCredits: {
    display: { xs: 'inline-flex', md: 'none' },
    alignItems: 'center',
    px: 1,
    py: 0.4,
    borderRadius: '999px',
    fontSize: 12,
    fontWeight: 700,
    color: colors.ORANGE_LIGHT,
    bgcolor: themeVars.accentBg,
    border: `1px solid ${themeVars.accentBorder}`,
  },
  mobileDrawer: {
    width: 'min(88vw, 380px)',
    bgcolor: colors.BG_PAPER,
    color: colors.TEXT_WHITE,
    borderLeft: `1px solid ${themeVars.border}`,
    backgroundImage: `linear-gradient(180deg, ${themeVars.accentBg} 0%, transparent 28%)`,
  },
  drawerHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: 2,
    pt: 2,
    pb: 1,
  },
  drawerLogo: {
    width: 48,
    cursor: 'pointer',
  },
  drawerSection: {
    px: 2,
    py: 1,
  },
  drawerSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: colors.TEXT_GRAY,
    mb: 1,
    px: 0.5,
  },
  drawerItem: (active?: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    px: 1.5,
    py: 1.25,
    mb: 0.5,
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: 15,
    fontWeight: 600,
    color: active ? colors.ORANGE_LIGHT : colors.TEXT_WHITE,
    bgcolor: active ? themeVars.accentBg : 'transparent',
    transition: 'background-color 0.2s',
    '&:hover': {
      bgcolor: themeVars.hover,
    },
  }),
  drawerUserCard: {
    mx: 2,
    mt: 0.5,
    mb: 1.5,
    p: 2,
    borderRadius: '18px',
    background: `linear-gradient(135deg, ${themeVars.accentBg} 0%, ${themeVars.surface} 55%)`,
    border: `1px solid ${themeVars.accentBorder}`,
    boxShadow: themeVars.shadow,
  },
  drawerUserRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    mb: 1.5,
  },
  drawerUserMeta: {
    flex: 1,
    minWidth: 0,
  },
  drawerUserName: {
    fontWeight: 800,
    fontSize: 17,
    color: colors.TEXT_WHITE,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    lineHeight: 1.25,
  },
  drawerUserEmail: {
    fontSize: 12,
    color: colors.TEXT_GRAY,
    mt: 0.25,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  drawerCreditsBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.75,
    py: 1.1,
    px: 1.5,
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 700,
    color: colors.ORANGE_LIGHT,
    bgcolor: themeVars.accentBg,
    border: `1px solid ${themeVars.accentBorder}`,
    transition: 'all 0.2s',
    '&:hover': {
      bgcolor: themeVars.hover,
      transform: 'translateY(-1px)',
    },
  },
  drawerQuickActions: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 0.75,
  },
  drawerQuickAction: (active?: boolean) => ({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.5,
    py: 1.25,
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 700,
    color: active ? colors.ORANGE_LIGHT : colors.TEXT_GRAY,
    bgcolor: active ? themeVars.accentBg : themeVars.surface,
    border: active
      ? `1px solid ${themeVars.accentBorder}`
      : `1px solid ${themeVars.borderSubtle}`,
    transition: 'all 0.2s',
    '&:hover': {
      color: colors.ORANGE_LIGHT,
      bgcolor: themeVars.accentBg,
    },
  }),
  drawerGuestCard: {
    mx: 2,
    mb: 1.5,
    p: 2,
    borderRadius: '18px',
    bgcolor: themeVars.surface,
    border: `1px dashed ${themeVars.border}`,
    textAlign: 'center',
  },
  drawerSettingsCard: {
    mx: 2,
    p: 1.5,
    borderRadius: '14px',
    bgcolor: themeVars.surface,
    border: `1px solid ${themeVars.borderSubtle}`,
  },
  drawerSettingsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    py: 1,
    '&:not(:last-child)': {
      borderBottom: `1px solid ${themeVars.borderSubtle}`,
      pb: 1.25,
      mb: 0.25,
    },
  },
  drawerSettingsLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: colors.TEXT_GRAY,
  },
  drawerLogoutItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    px: 1.5,
    py: 1.25,
    mt: 0.5,
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: 15,
    fontWeight: 600,
    color: '#c62828',
    bgcolor: 'rgba(198, 40, 40, 0.08)',
    border: '1px solid rgba(198, 40, 40, 0.25)',
    transition: 'all 0.2s',
    '&:hover': {
      bgcolor: 'rgba(198, 40, 40, 0.14)',
    },
  },
  drawerFooter: {
    mt: 'auto',
    p: 2,
    borderTop: `1px solid ${themeVars.borderSubtle}`,
  },
  loginBtnWrap: {
    width: '100%',
  },
};
