import { ToolPageStyles } from '../shared/ToolPage.styles';
import { colors } from '../../constants/styles';

export const AvatarStyles = {
  container: ToolPageStyles.page,
  ...ToolPageStyles,
  inputContainer: ToolPageStyles.panelSection,
  inputGrid: ToolPageStyles.inputRow,
  imageUploadButton: {
    border: '1px solid rgba(255,255,255,0.12)',
    width: '100%',
    aspectRatio: '1',
    borderRadius: '14px',
    transition: 'all 0.25s',
    cursor: 'pointer',
    bgcolor: 'rgba(255,255,255,0.04)',
    '&:hover': {
      borderColor: 'rgba(255, 140, 80, 0.4)',
    },
  },
  imagePreview: {
    background: 'center center / contain no-repeat',
    width: '100%',
    aspectRatio: '1',
    borderRadius: '14px',
    cursor: 'pointer',
  },
  stylesContainer: ToolPageStyles.stylesSection,
  stylesGrid: {
    flexWrap: 'wrap',
    justifyContent: 'center',
    maxWidth: 720,
    mx: 'auto',
  },
  tabsContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: 0.5,
    mb: 1.5,
    mt: 2,
  },
  tab: {
    px: 2,
    py: 1,
    borderRadius: '10px',
    cursor: 'pointer',
    color: colors.TEXT_GRAY,
    fontSize: 14,
    fontWeight: 600,
    transition: 'all 0.2s',
    '&:hover': { color: colors.TEXT_WHITE },
  },
  tabActive: {
    px: 2,
    py: 1,
    borderRadius: '10px',
    cursor: 'pointer',
    bgcolor: 'rgba(255, 140, 80, 0.2)',
    color: colors.ORANGE_LIGHT,
    border: '1px solid rgba(255, 140, 80, 0.35)',
    fontSize: 14,
    fontWeight: 700,
  },
  emojiCircle: {
    width: { md: 72, xs: 56 },
    height: { md: 72, xs: 56 },
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    bgcolor: 'rgba(255,255,255,0.06)',
    fontSize: { md: 32, xs: 24 },
    border: '1px solid rgba(255,255,255,0.08)',
  },
};
