import { colors } from '../../constants/styles';

export const RemoveBgStyles = {
  container: {
    padding: { md: '12px 64px', xs: '8px 32px' },
  },
  title: {
    color: colors.ORANGE_LIGHT,
    textAlign: 'center',
    fontSize: { md: '48px', xs: '32px' },
    fontWeight: '900',
  },
  titleAccent: {
    color: colors.TEXT_WHITE,
    textAlign: 'center',
    fontSize: { md: '48px', xs: '32px' },
    fontWeight: '900',
  },
  description: {
    color: colors.TEXT_GRAY,
    textAlign: 'center',
    fontSize: { md: '18px', xs: '16px' },
    fontWeight: '300',
    marginBottom: '32px',
  },
  uploadArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    border: `2px dashed ${colors.TEXT_GRAY}`,
    borderRadius: '16px',
    padding: '64px 32px',
    cursor: 'pointer',
    transition: '.3s',
    maxWidth: '600px',
    margin: '0 auto',
    '&:hover': {
      borderColor: colors.ORANGE_LIGHT,
      '& svg': {
        fill: colors.ORANGE_LIGHT,
      },
    },
  },
  uploadText: {
    color: colors.TEXT_GRAY,
    fontSize: '16px',
    marginTop: '12px',
  },
  sliderContainer: {
    maxWidth: '500px',
    margin: '0 auto',
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '16px',
    userSelect: 'none',
  },
  sliderImage: {
    display: 'block',
    width: '100%',
    height: 'auto',
  },
  sliderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    overflow: 'hidden',
  },
  sliderHandle: {
    position: 'absolute',
    top: 0,
    width: '4px',
    height: '100%',
    backgroundColor: colors.ORANGE_LIGHT,
    cursor: 'ew-resize',
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sliderKnob: {
    maxWidth: '24px',
    maxHeight: '24px',
    borderRadius: '50%',
    backgroundColor: colors.ORANGE_LIGHT,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  },
  sliderLabel: {
    position: 'absolute',
    bottom: '12px',
    padding: '4px 12px',
    borderRadius: '8px',
    backgroundColor: 'rgba(0,0,0,0.6)',
    color: colors.TEXT_WHITE,
    fontSize: '13px',
    fontWeight: '600',
    zIndex: 5,
    pointerEvents: 'none',
  },
  buttonsContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '16px',
    marginTop: '32px',
    marginBottom: '32px',
  },
  checkerboard: {
    backgroundColor: '#fff',
    backgroundImage:
      'linear-gradient(45deg, #e0e0e0 25%, transparent 25%), linear-gradient(-45deg, #e0e0e0 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #e0e0e0 75%), linear-gradient(-45deg, transparent 75%, #e0e0e0 75%)',
    backgroundSize: '16px 16px',
    backgroundPosition: '0 0, 0 8px, 8px -8px, -8px 0px',
  },
};
